import { v4 as uuidv4 } from "uuid";

export const SECTION_TYPES = {
  HERO: "hero",
  FEATURES: "features",
  CTA: "cta",
  CONTENT: "content",
  GALLERY: "gallery",
  TESTIMONIALS: "testimonials",
  PRICING: "pricing",
  CONTACT: "contact",
  TEAM: "team",
  FAQ: "faq",
  STATS: "stats",
  NEWSLETTER: "newsletter",
  PROCESS: "process",
  BENEFITS: "benefits",
  LOGOS: "logos",
  CASE_STUDIES: "case-studies",
  TRUST: "trust",
  HEADER: "header",
  FOOTER: "footer",
};

export const SECTION_VARIANTS = {
  [SECTION_TYPES.HEADER]: [
    { value: "default", label: "Logo Left, Nav Right" },
    { value: "centered", label: "Centered Logo" },
    { value: "nav-left", label: "Nav Left, Logo Right" },
    { value: "minimal", label: "Minimal" },
    { value: "split", label: "Split (Nav both sides)" },
  ],
  [SECTION_TYPES.FOOTER]: [
    { value: "columns", label: "Multi-Column" },
    { value: "simple", label: "Simple" },
    { value: "centered", label: "Centered" },
    { value: "minimal", label: "Minimal" },
  ],
  [SECTION_TYPES.HERO]: [
    { value: "centered", label: "Centered" },
    { value: "split", label: "Split (with image)" },
    { value: "carousel", label: "Carousel / Slideshow" },
  ],
  [SECTION_TYPES.FEATURES]: [
    { value: "grid", label: "Grid" },
    { value: "list", label: "List" },
  ],
  [SECTION_TYPES.GALLERY]: [
    { value: "grid", label: "Grid" },
    { value: "carousel", label: "Carousel" },
  ],
  [SECTION_TYPES.TESTIMONIALS]: [
    { value: "grid", label: "Grid" },
    { value: "carousel", label: "Carousel" },
  ],
  [SECTION_TYPES.LOGOS]: [
    { value: "grid", label: "Grid" },
    { value: "carousel", label: "Scrolling Carousel" },
  ],
  [SECTION_TYPES.PROCESS]: [
    { value: "timeline", label: "Timeline" },
    { value: "grid", label: "Grid" },
  ],
  [SECTION_TYPES.BENEFITS]: [
    { value: "grid", label: "Grid (with metrics)" },
    { value: "list", label: "List" },
  ],
  [SECTION_TYPES.CTA]: [
    { value: "simple", label: "Simple" },
    { value: "features", label: "With Features List" },
  ],
  [SECTION_TYPES.CONTENT]: [
    { value: "text", label: "Text Only" },
    { value: "image", label: "Text + Image" },
  ],
  [SECTION_TYPES.STATS]: [
    { value: "row", label: "Row" },
    { value: "headline", label: "With Headline" },
  ],
};

export const SECTION_LIBRARY = [
  {
    id: "header",
    type: SECTION_TYPES.HEADER,
    name: "Header / Navigation",
    icon: "layout",
    category: "structure",
    defaultProps: {
      variant: "default",
      showLogo: true,
      logo: "",
      logoText: "Brand",
      showNav: true,
      menu: [
        { id: uuidv4(), label: "Home", url: "/", hasSubmenu: false, submenu: [] },
        { id: uuidv4(), label: "About", url: "/about", hasSubmenu: false, submenu: [] },
        {
          id: uuidv4(), label: "Services", url: "/services", hasSubmenu: true,
          submenu: [
            { id: uuidv4(), label: "Web Design", url: "/services/web-design" },
            { id: uuidv4(), label: "Development", url: "/services/development" },
            { id: uuidv4(), label: "SEO", url: "/services/seo" },
          ],
        },
        { id: uuidv4(), label: "Contact", url: "/contact", hasSubmenu: false, submenu: [] },
      ],
      showCta: true,
      ctaText: "Get Started",
      ctaLink: "#",
      ctaStyle: "filled",
      showSearch: false,
      transparent: false,
      blur: false,
      sticky: true,
      textColor: "#111827",
      backgroundColor: "#ffffff",
      ctaColor: "#6366f1",
      ctaTextColor: "#ffffff",
      height: "80px",
      borderBottom: true,
      borderColor: "#e5e7eb",
    },
  },
  {
    id: "footer",
    type: SECTION_TYPES.FOOTER,
    name: "Footer",
    icon: "minus-square",
    category: "structure",
    defaultProps: {
      variant: "columns",
      showLogo: true,
      logo: "",
      logoText: "Brand",
      tagline: "Building amazing products since 2020.",
      columns: [
        {
          id: uuidv4(), title: "Company",
          links: [
            { id: uuidv4(), label: "About", url: "/about" },
            { id: uuidv4(), label: "Careers", url: "/careers" },
            { id: uuidv4(), label: "Blog", url: "/blog" },
          ],
        },
        {
          id: uuidv4(), title: "Product",
          links: [
            { id: uuidv4(), label: "Features", url: "#features" },
            { id: uuidv4(), label: "Pricing", url: "#pricing" },
            { id: uuidv4(), label: "FAQ", url: "#faq" },
          ],
        },
        {
          id: uuidv4(), title: "Legal",
          links: [
            { id: uuidv4(), label: "Privacy Policy", url: "/privacy" },
            { id: uuidv4(), label: "Terms of Service", url: "/terms" },
          ],
        },
      ],
      showNewsletter: false,
      newsletter: {
        title: "Stay Updated",
        placeholder: "Enter your email",
        buttonText: "Subscribe",
        successMessage: "Thanks for subscribing!",
        errorMessage: "Something went wrong.",
      },
      showSocial: true,
      socialLinks: [
        { id: uuidv4(), platform: "Twitter", icon: "twitter", url: "#" },
        { id: uuidv4(), platform: "LinkedIn", icon: "linkedin", url: "#" },
        { id: uuidv4(), platform: "GitHub", icon: "github", url: "#" },
      ],
      copyright: `© ${new Date().getFullYear()} Brand. All rights reserved.`,
      backgroundColor: "#111827",
      textColor: "#ffffff",
      linkColor: "#9ca3af",
      linkHoverColor: "#ffffff",
      accentColor: "#6366f1",
      logoTextColor: "#ffffff",
      taglineColor: "#9ca3af",
      columnTitleColor: "#ffffff",
      padding: "3rem 0",
      showDivider: true,
      dividerColor: "rgba(255,255,255,0.1)",
      copyrightColor: "rgba(255,255,255,0.5)",
    },
  },
  {
    id: "hero",
    type: SECTION_TYPES.HERO,
    name: "Hero",
    icon: "layout",
    defaultProps: {
      variant: "centered",
      heading: "Transform Your Digital Presence",
      subheading: "Build amazing websites in minutes with our intuitive platform",
      ctaText: "Get Started Free",
      ctaLink: "#",
      ctaColor: "#6366f1",
      ctaTextColor: "#ffffff",
      secondaryCtaText: "",
      secondaryCtaLink: "#",
      secondaryCtaColor: "transparent",
      secondaryCtaBorderColor: "#e5e7eb",
      secondaryCtaTextColor: "#374151",
      headingColor: "#111827",
      subheadingColor: "#6b7280",
      alignment: "center",
      image: "",
      carousel: {
        enabled: false,
        autoplay: true,
        interval: 5000,
        slides: [
          { id: uuidv4(), image: "", heading: "Transform Your Digital Presence", subheading: "Build amazing websites in minutes", ctaText: "Get Started", ctaLink: "#" },
          { id: uuidv4(), image: "", heading: "Powerful Features", subheading: "Everything you need to succeed online", ctaText: "Learn More", ctaLink: "#" },
        ],
      },
    },
  },
  {
    id: "features",
    type: SECTION_TYPES.FEATURES,
    name: "Features",
    icon: "zap",
    defaultProps: {
      variant: "grid",
      heading: "Everything You Need",
      subheading: "Powerful features to help you succeed",
      headingColor: "#111827",
      subheadingColor: "#6b7280",
      cardBackground: "#ffffff",
      cardBorderColor: "#f3f4f6",
      iconBackground: "#6366f1",
      iconColor: "#ffffff",
      titleColor: "#111827",
      descriptionColor: "#6b7280",
      features: [
        { id: uuidv4(), icon: "zap", title: "Lightning Fast", description: "Optimized for speed with instant load times" },
        { id: uuidv4(), icon: "shield", title: "Secure & Safe", description: "Enterprise-grade security built-in" },
        { id: uuidv4(), icon: "smartphone", title: "Mobile Ready", description: "Perfect on every device and screen size" },
        { id: uuidv4(), icon: "globe", title: "Global CDN", description: "Fast delivery worldwide" },
        { id: uuidv4(), icon: "code", title: "Developer Friendly", description: "Custom code when you need it" },
        { id: uuidv4(), icon: "trending-up", title: "SEO Optimized", description: "Rank higher in search results" },
      ],
      columns: 3,
    },
  },
  {
    id: "stats",
    type: SECTION_TYPES.STATS,
    name: "Stats & Numbers",
    icon: "bar-chart",
    defaultProps: {
      variant: "row",
      heading: "Our Impact",
      subheading: "Numbers speak louder than words",
      headingColor: "#111827",
      subheadingColor: "#6b7280",
      valueColor: "#6366f1",
      labelColor: "#111827",
      descriptionColor: "#6b7280",
      stats: [
        { id: uuidv4(), value: "100K+", label: "Active Users", description: "Worldwide" },
        { id: uuidv4(), value: "99.9%", label: "Uptime", description: "Guaranteed" },
        { id: uuidv4(), value: "4.9/5", label: "Rating", description: "Customer satisfaction" },
        { id: uuidv4(), value: "24/7", label: "Support", description: "Always available" },
      ],
    },
  },
  {
    id: "process",
    type: SECTION_TYPES.PROCESS,
    name: "Process",
    icon: "clock",
    defaultProps: {
      variant: "timeline",
      heading: "How It Works",
      subheading: "Simple steps to get started",
      headingColor: "#111827",
      subheadingColor: "#6b7280",
      iconBackground: "#6366f1",
      iconColor: "#ffffff",
      stepTitleColor: "#111827",
      stepDescColor: "#6b7280",
      stepDurationColor: "#6366f1",
      numberColor: "#6366f1",
      steps: [
        { id: uuidv4(), icon: "edit", title: "Plan", description: "Define your goals and requirements", duration: "1–2 days", number: "01" },
        { id: uuidv4(), icon: "code", title: "Build", description: "Create your website with our tools", duration: "3–5 days", number: "02" },
        { id: uuidv4(), icon: "rocket", title: "Launch", description: "Deploy and go live instantly", duration: "Same day", number: "03" },
      ],
    },
  },
  {
    id: "content",
    type: SECTION_TYPES.CONTENT,
    name: "Content / About",
    icon: "file-text",
    defaultProps: {
      variant: "text",
      heading: "Our Story",
      headingColor: "#111827",
      contentColor: "#374151",
      content: "<p>We believe in building tools that empower everyone to create amazing websites. Our platform combines simplicity with powerful features.</p><p>Join thousands of creators who have already transformed their online presence.</p>",
      image: "",
      imagePosition: "right",
    },
  },
  {
    id: "gallery",
    type: SECTION_TYPES.GALLERY,
    name: "Gallery / Portfolio",
    icon: "image",
    defaultProps: {
      variant: "grid",
      heading: "Our Work",
      subheading: "Explore our latest projects",
      headingColor: "#111827",
      subheadingColor: "#6b7280",
      overlayColor: "rgba(0,0,0,0.7)",
      titleColor: "#ffffff",
      categoryColor: "#d1d5db",
      items: [
        { id: uuidv4(), image: "", title: "Project Alpha", category: "Design", description: "A modern web design project" },
        { id: uuidv4(), image: "", title: "Project Beta", category: "Development", description: "Custom web application" },
        { id: uuidv4(), image: "", title: "Project Gamma", category: "Branding", description: "Complete brand identity" },
        { id: uuidv4(), image: "", title: "Project Delta", category: "Marketing", description: "Digital marketing campaign" },
        { id: uuidv4(), image: "", title: "Project Epsilon", category: "E-commerce", description: "Online store platform" },
        { id: uuidv4(), image: "", title: "Project Zeta", category: "Mobile", description: "Cross-platform app" },
      ],
      columns: 3,
      carousel: { enabled: false, autoplay: true, interval: 5000 },
    },
  },
  {
    id: "testimonials",
    type: SECTION_TYPES.TESTIMONIALS,
    name: "Testimonials",
    icon: "message-square",
    defaultProps: {
      variant: "grid",
      heading: "What Our Customers Say",
      subheading: "Real feedback from real people",
      headingColor: "#111827",
      subheadingColor: "#6b7280",
      cardBackground: "#ffffff",
      quoteColor: "#374151",
      nameColor: "#111827",
      roleColor: "#6b7280",
      metricColor: "#6366f1",
      starColor: "#f59e0b",
      testimonials: [
        { id: uuidv4(), name: "Sarah Mitchell", role: "Creative Director", content: "This platform transformed how we build websites.", avatar: "", rating: 5 },
        { id: uuidv4(), name: "James Chen", role: "Startup Founder", content: "Finally, a website builder that doesn't limit creativity.", avatar: "", rating: 5 },
        { id: uuidv4(), name: "Emily Rodriguez", role: "Marketing Manager", content: "The ROI has been incredible. We launched in days.", avatar: "", rating: 5, metric: "300% increase" },
      ],
      carousel: { enabled: false, autoplay: true, interval: 5000 },
    },
  },
  {
    id: "logos",
    type: SECTION_TYPES.LOGOS,
    name: "Logos / Partners",
    icon: "shield",
    defaultProps: {
      variant: "grid",
      heading: "Trusted by Industry Leaders",
      subheading: "Join thousands of companies using our platform",
      headingColor: "#111827",
      subheadingColor: "#6b7280",
      logoFilter: "grayscale",
      logos: [
        { id: uuidv4(), image: "", name: "Company 1", width: "120" },
        { id: uuidv4(), image: "", name: "Company 2", width: "120" },
        { id: uuidv4(), image: "", name: "Company 3", width: "120" },
        { id: uuidv4(), image: "", name: "Company 4", width: "120" },
        { id: uuidv4(), image: "", name: "Company 5", width: "120" },
        { id: uuidv4(), image: "", name: "Company 6", width: "120" },
      ],
      columns: 4,
      carousel: { enabled: false, autoplay: true, interval: 3000 },
    },
  },
  {
    id: "benefits",
    type: SECTION_TYPES.BENEFITS,
    name: "Benefits",
    icon: "award",
    defaultProps: {
      variant: "grid",
      heading: "Why Choose Us",
      subheading: "The advantages of working with us",
      headingColor: "#111827",
      subheadingColor: "#6b7280",
      cardBackground: "#ffffff",
      iconBackground: "#6366f1",
      iconColor: "#ffffff",
      titleColor: "#111827",
      descriptionColor: "#6b7280",
      metricColor: "#6366f1",
      benefits: [
        { id: uuidv4(), icon: "zap", title: "Lightning Fast", description: "10x faster performance", metric: "99.9%" },
        { id: uuidv4(), icon: "shield", title: "Bank Level Security", description: "Enterprise encryption", metric: "256-bit" },
        { id: uuidv4(), icon: "headphones", title: "24/7 Support", description: "Always here to help", metric: "< 5min" },
        { id: uuidv4(), icon: "trending-up", title: "Proven Results", description: "Average 3x ROI", metric: "+300%" },
      ],
    },
  },
  {
    id: "cta",
    type: SECTION_TYPES.CTA,
    name: "Call to Action",
    icon: "target",
    defaultProps: {
      variant: "simple",
      heading: "Ready to Get Started?",
      subheading: "Join thousands of satisfied customers today",
      headingColor: "#ffffff",
      subheadingColor: "rgba(255,255,255,0.85)",
      featureColor: "rgba(255,255,255,0.75)",
      primaryButton: { text: "Start Free Trial", link: "#", backgroundColor: "#ffffff", textColor: "#6366f1" },
      secondaryButton: { text: "Contact Sales", link: "#", borderColor: "#ffffff", textColor: "#ffffff" },
      features: ["No credit card required", "14-day free trial", "Cancel anytime"],
    },
  },
  {
    id: "pricing",
    type: SECTION_TYPES.PRICING,
    name: "Pricing",
    icon: "dollar-sign",
    defaultProps: {
      heading: "Choose Your Plan",
      subheading: "Flexible pricing that grows with you",
      headingColor: "#111827",
      subheadingColor: "#6b7280",
      cardBackground: "#ffffff",
      cardBorderColor: "#e5e7eb",
      highlightColor: "#6366f1",
      planNameColor: "#111827",
      planPriceColor: "#111827",
      planDescColor: "#6b7280",
      featureColor: "#374151",
      checkColor: "#22c55e",
      plans: [
        { id: uuidv4(), name: "Starter", price: "$12", period: "month", description: "Perfect for individuals", features: ["5 Projects", "10GB Storage", "Basic Support"], ctaText: "Get Started", ctaLink: "#", highlighted: false },
        { id: uuidv4(), name: "Pro", price: "$39", period: "month", description: "For professionals", features: ["Unlimited Projects", "100GB Storage", "Priority Support", "Advanced Features"], ctaText: "Start Trial", ctaLink: "#", highlighted: true, badge: "Most Popular" },
        { id: uuidv4(), name: "Enterprise", price: "Custom", period: "", description: "For large teams", features: ["Everything in Pro", "Unlimited Storage", "Dedicated Support", "Custom Features"], ctaText: "Contact Us", ctaLink: "#", highlighted: false },
      ],
    },
  },
  {
    id: "contact",
    type: SECTION_TYPES.CONTACT,
    name: "Contact Form",
    icon: "mail",
    defaultProps: {
      heading: "Get In Touch",
      subheading: "We'd love to hear from you",
      headingColor: "#111827",
      subheadingColor: "#6b7280",
      cardBackground: "#ffffff",
      labelColor: "#374151",
      inputBorderColor: "#e5e7eb",
      inputFocusColor: "#6366f1",
      buttonColor: "#6366f1",
      buttonTextColor: "#ffffff",
      submitText: "Send Message",
      successMessage: "Thanks! We'll get back to you soon.",
      errorMessage: "Something went wrong. Please try again.",
      fields: [
        { id: uuidv4(), type: "text", label: "Name", placeholder: "Your name", required: true },
        { id: uuidv4(), type: "email", label: "Email", placeholder: "your@email.com", required: true },
        { id: uuidv4(), type: "textarea", label: "Message", placeholder: "Your message...", required: true },
      ],
    },
  },
  {
    id: "team",
    type: SECTION_TYPES.TEAM,
    name: "Team",
    icon: "users",
    defaultProps: {
      heading: "Meet Our Team",
      subheading: "The people behind the product",
      headingColor: "#111827",
      subheadingColor: "#6b7280",
      nameColor: "#111827",
      roleColor: "#6366f1",
      bioColor: "#6b7280",
      members: [
        { id: uuidv4(), name: "Olivia Chen", role: "Creative Director", bio: "Leading design with passion and precision", image: "", socials: {} },
        { id: uuidv4(), name: "Marcus Thompson", role: "Head of Product", bio: "Building tools that empower creators", image: "", socials: {} },
        { id: uuidv4(), name: "Yuki Tanaka", role: "Lead Engineer", bio: "Crafting elegant technical solutions", image: "", socials: {} },
      ],
      columns: 3,
    },
  },
  {
    id: "faq",
    type: SECTION_TYPES.FAQ,
    name: "FAQ",
    icon: "help-circle",
    defaultProps: {
      heading: "Frequently Asked Questions",
      subheading: "Everything you need to know",
      headingColor: "#111827",
      subheadingColor: "#6b7280",
      cardBackground: "#ffffff",
      cardBorderColor: "#e5e7eb",
      questionColor: "#111827",
      answerColor: "#6b7280",
      badgeBackground: "#6366f1",
      badgeTextColor: "#ffffff",
      faqs: [
        { id: uuidv4(), question: "Do I need coding knowledge?", answer: "Not at all! Our platform is designed for everyone." },
        { id: uuidv4(), question: "Can I use my own domain?", answer: "Yes! You can connect any domain you own or purchase a new one." },
        { id: uuidv4(), question: "What kind of websites can I build?", answer: "Anything you can imagine! From portfolios to online stores." },
      ],
    },
  },
  {
    id: "newsletter",
    type: SECTION_TYPES.NEWSLETTER,
    name: "Newsletter",
    icon: "mail",
    defaultProps: {
      heading: "Stay Updated",
      subheading: "Get the latest news and updates delivered to your inbox",
      headingColor: "#ffffff",
      subheadingColor: "rgba(255,255,255,0.85)",
      inputBackground: "rgba(255,255,255,0.1)",
      inputTextColor: "#ffffff",
      inputBorderColor: "transparent",
      buttonColor: "#ffffff",
      buttonTextColor: "#6366f1",
      benefitColor: "rgba(255,255,255,0.75)",
      placeholder: "Enter your email",
      buttonText: "Subscribe",
      successMessage: "Thanks for subscribing!",
      errorMessage: "Something went wrong. Please try again.",
      benefits: ["Weekly insights", "Exclusive content", "Early access"],
    },
  },
  {
    id: "case-studies",
    type: SECTION_TYPES.CASE_STUDIES,
    name: "Case Studies",
    icon: "book-open",
    defaultProps: {
      heading: "Success Stories",
      subheading: "See how our clients have grown",
      headingColor: "#111827",
      subheadingColor: "#6b7280",
      cardBackground: "#ffffff",
      titleColor: "#111827",
      descriptionColor: "#6b7280",
      clientBadgeBackground: "#f3f4f6",
      clientBadgeColor: "#6b7280",
      resultBadgeBackground: "#dcfce7",
      resultBadgeColor: "#166534",
      metricValueColor: "#6366f1",
      metricLabelColor: "#6b7280",
      studies: [
        { id: uuidv4(), title: "Platform Redesign", client: "Acme Inc.", description: "Complete redesign resulting in 3x conversion improvement.", image: "", link: "#", results: ["3x Conversion", "50% Bounce Reduction"], metrics: [{ value: "+300%", label: "Conversion" }, { value: "-50%", label: "Bounce Rate" }, { value: "2mo", label: "Timeline" }] },
        { id: uuidv4(), title: "E-Commerce Launch", client: "ShopCo", description: "Launched a new online store from zero to $1M ARR in six months.", image: "", link: "#", results: ["$1M ARR", "100K Users"], metrics: [{ value: "$1M", label: "ARR" }, { value: "100K", label: "Users" }, { value: "6mo", label: "To Launch" }] },
      ],
    },
  },
  {
    id: "trust",
    type: SECTION_TYPES.TRUST,
    name: "Trust & Security",
    icon: "shield-check",
    defaultProps: {
      heading: "Trusted & Secure",
      subheading: "Your data is safe with us",
      headingColor: "#111827",
      subheadingColor: "#6b7280",
      iconBackground: "#eef2ff",
      iconColor: "#6366f1",
      badgeTitleColor: "#111827",
      badgeDescColor: "#6b7280",
      awardBackground: "#ffffff",
      awardBorderColor: "#e5e7eb",
      awardTextColor: "#374151",
      badges: [
        { id: uuidv4(), icon: "shield", title: "SOC 2 Certified", description: "Enterprise security standards" },
        { id: uuidv4(), icon: "lock", title: "256-bit Encryption", description: "Bank-level data protection" },
        { id: uuidv4(), icon: "check-circle", title: "GDPR Compliant", description: "Full privacy regulation adherence" },
        { id: uuidv4(), icon: "award", title: "ISO 27001", description: "International security certification" },
      ],
      testimonials: [],
      awards: ["G2 Leader 2024", "Product Hunt #1", "Forbes Top 100"],
    },
  },
];

export const createNewSection = (libraryItem) => {
  const isStructural = libraryItem.type === SECTION_TYPES.HEADER || libraryItem.type === SECTION_TYPES.FOOTER;
  return {
    id: `section-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    type: libraryItem.type,
    templateId: libraryItem.id,
    props: JSON.parse(JSON.stringify(libraryItem.defaultProps)),
    style: isStructural ? {} : {
      padding: { top: "4rem", bottom: "4rem" },
      backgroundType: "color",
      backgroundColor: "transparent",
      backgroundGradient: "",
      backgroundImage: "",
      backgroundOverlay: 0,
    },
  };
};